# config2.yaml 1.2

global:
  # Configuration file
  config:
    value: "/spindles/shred/ShredSync2.0/config2.yaml"
    help: "Specify configuration file."
    command_argument: "--config"
    short_option: "-c"  # Short option for the config file

  # Source Paths
  shredded_source:
    value: "/nfs/shred/cache"
    help: "Path to the shredded source folder."
    command_argument: "--shredded-source"
    short_option: "-d"  # Short option for shredded source folder
  shredded_source_recursive:
    value: "no"
    help: "Whether to search the shredded source folder recursively."
    command_argument: "--shredded-source-recursive"
    short_option: "-r"  # Short option for recursive search in shredded source
  import_source:
    value: "/nfs/shred/backup/shred_backup"
    help: "Path to the import source folder."
    command_argument: "--import-source"
    short_option: "-i"  # Short option for import source folder
  import_source_recursive:
    value: "no"
    help: "Whether to search the import source folder recursively."
    command_argument: "--import-source-recursive"
    short_option: "-I"  # Short option for recursive search in import source

  # Log Settings
  shred_log_source:
    value: "/nfs/shred/cache/logs/"
    help: "Path to the shred logs folder."
    command_argument: "--shred-log-source"
    short_option: "-L"  # Short option for shred log source folder
  logpath:
    value: "/spindles/shred/log"
    help: "Root logs folder."
    command_argument: "--logpath"
    short_option: "-p"  # Short option for log path
  log_format:
    value: "%(asctime)s - %(levelname)s - %(message)s"
    help: "Logging format."
    command_argument: "--log-format"
    short_option: "-F"  # Short option for log format
  log_dir_permission:
    value: "0755"
    help: "Permissions for the log directory."
    command_argument: "--log-dir-permission"
    short_option: "-P"  # Short option for log directory permission
  log_file_permission:
    value: "0644"
    help: "Permissions for the log file."
    command_argument: "--log-file-permission"
    short_option: "-f"  # Short option for log file permission

  # Shred Timing
  shred_log_prior:
    value: "2"
    help: "How many days prior to look behind."
    command_argument: "--shred-log-prior"
    short_option: "-b"  # Short option for prior days
  shred_log_after:
    value: "1"
    help: "How many days after to look ahead."
    command_argument: "--shred-log-after"
    short_option: "-a"  # Short option for after days

  # Destination and Database
  destination:
    value: "/spindles/shred/ShredTV"
    help: "Path to the processing output."
    command_argument: "--destination"
    short_option: "-t"  # Short option for destination
  db_path:
    value: "/spindles/shred/db/"
    help: "Root database path."
    command_argument: "--db-path"
    short_option: "-D"  # Short option for database path

  # System Permissions
  umask:
    value: "002"
    help: "Default umask for created files and folders."
    command_argument: "--umask"
    short_option: "-u"  # Short option for umask

shredsync:
  logfile:
    value: "shredsync.log"
    help: "ShredSync log file."
    command_argument: "--shredsync-logfile"
    short_option: "-l"  # Short option for shredsync logfile
  history_file:
    value: "/spindles/shred/log/processed_folders.log"
    help: "Log file for processed items. Will be removed in future release."
    command_argument: "--history-file"
    short_option: "-H"  # Short option for history file

  # Action and Threshold Settings
  action:
    value: "rsync"
    help: "Sync command {rsync,move}."
    command_argument: "--action"
    short_option: "-A"  # Short option for action
  days_threshold:
    value: 60
    help: "Days older than this value will be removed from source."
    command_argument: "--days-threshold"
    short_option: "-T"  # Short option for days threshold

  # Rsync and Move Options
  rsync_options:
    value: "-ahvP --info=progress2"
    help: "rsync options."
    command_argument: "--rsync-options"
    short_option: "-R"  # Short option for rsync options
  move_options:
    value: "default"
    help: "Reserved for potential future use."
    command_argument: "--move-options"
    short_option: "-M"  # Short option for move options

  # Database
  db_file:
    value: "shredsync.db"
    help: "Database file for shredsync."
    command_argument: "--shredsync-db-file"
    short_option: "-B"  # Short option for shredsync database file

shredmatch:
  logfile:
    value: "shredmatch.log"
    help: "ShredMatch log file."
    command_argument: "--shredmatch-logfile"
    short_option: "-s"  # Short option for shredmatch logfile
  db_file:
    value: "shredmatch.db"
    help: "Database file for ShredMatch."
    command_argument: "--shredmatch-db-file"
    short_option: "-m"  # Short option for shredmatch database file